version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - '@vitest/*'
          - 'eslint'
          - 'prettier'
          - 'tsup'
          - 'turbo'
          - 'typescript'
          - 'vitest'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
      dev-dependencies:
        patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - '@vitest/*'
          - 'eslint'
          - 'prettier'
          - 'tsup'
          - 'turbo'
          - 'typescript'
          - 'vitest'
        update-types:
          - 'minor'
          - 'patch'
